[package]
name = "web3_console"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "1.0.2"
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
